location/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve
from django.urls import path, include

from regions.views import IndexPageView, AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexPageView.as_view(), name='index'),
    path('about/', AboutView.as_view(), name='about'),
    path('regions/', include('regions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += [
        re_path(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

regions/urls.py
from django.urls import include, path


from . import views

urlpatterns = [
    #path('', views.IndexPageView.as_view(), name='index'),
    path('continent/create/', views.ContinentCreateView.as_view(), name='continent_create'),
    path('subcontinent/create/', views.SubContinentCreateView.as_view(), name='subcontinent_create'),
    path('country/create/', views.CountryCreateView.as_view(), name='country_create'),    
    path('state/create/', views.StateCreateView.as_view(), name='state_create'),
    path('city/create/', views.CityCreateView.as_view(), name='city_create'),
    path('timezone/create/', views.TimeZoneCreateView.as_view(), name='timezone_create'),


    path('continent/<int:pk>/subcontinent/', views.ContinentSubContinentListView.as_view(), name='continentsubcontinent_list'),
    path('subcontinent/<int:pk>/country/', views.SubContinentCountryListView.as_view(), name='subcontinentcountry_list'),
    path('country/<int:pk>/state/', views.CountryStateListView.as_view(), name='countrystate_list'),
    path('state/<int:pk>/city/', views.StateCityListView.as_view(), name='statecity_list'),
    path('countrycity/list/<int:pk>/', views.CountryCityListView.as_view(), name='countrycity_list'),


    path('continent/index/', views.ContinentIndexView.as_view(), name='continent_index'),
    path('subcontinent/index/', views.SubContinentIndexView.as_view(), name='subcontinent_index'),
    path('country/index/', views.CountryIndexView.as_view(), name='country_index'),
    #path('countrycity/index/', views.CountryCityIndexView.as_view(), name='countrycity_index'),
    path('state/index/', views.StateIndexView.as_view(), name='state_index'),
    path('city/index/', views.CityIndexView.as_view(), name='city_index'),
    path('timezone/index/', views.TimeZoneIndexView.as_view(), name='timezone_index'),

    
    path('continent/import/', views.continent_import, name='continent_import'),
    path('subcontinent/import/', views.subcontinent_import, name='subcontinent_import'),
    path('country/import/', views.country_import, name='country_import'),
    path('state/import/', views.state_import, name='state_import'),
    path('city/import/', views.city_import, name='city_import'),
    path('timezone/import/', views.timezone_import, name='timezone_import'),


    path('continent/<int:pk>/delete/', views.ContinentDeleteView.as_view(), name='continent_confirm_delete'),
    path('subcontinent/<int:pk>/delete/', views.SubContinentDeleteView.as_view(), name='subcontinent_confirm_delete'),
    path('country/<int:pk>/delete/', views.CountryDeleteView.as_view(), name='country_confirm_delete'),
    path('state/<int:pk>/delete/', views.StateDeleteView.as_view(), name='state_confirm_delete'),
    path('city/<int:pk>/delete/', views.CityDeleteView.as_view(), name='city_confirm_delete'),
    path('timezone/<int:pk>/delete/', views.TimeZoneDeleteView.as_view(), name='timezone_confirm_delete'),


    path('timezone/<int:pk>/update/', views.TimeZoneUpdateView.as_view(), name='timezone_update'),
    path('continent/<int:pk>/update/', views.ContinentUpdateView.as_view(), name='continent_update'),
    path('subcontinent/<int:pk>/update/', views.SubContinentUpdateView.as_view(), name='subcontinent_update'),
    path('country/<int:pk>/update/', views.CountryUpdateView.as_view(), name='country_update'),
    path('state/<int:pk>/update/', views.StateUpdateView.as_view(), name='state_update'),
    path('city/<int:pk>/update/', views.CityUpdateView.as_view(), name='city_update'),

    path('continent/<int:pk>/detail/', views.ContinentDetailView.as_view(), name='continent_detail'),
    path('subcontinent/<int:pk>/detail/', views.SubContinentDetailView.as_view(), name='subcontinent_detail'),
    path('country/<int:pk>/detail/', views.CountryDetailView.as_view(), name='country_detail'),
    path('state/<int:pk>/detail/', views.StateDetailView.as_view(), name='state_detail'),
    path('city/<int:pk>/detail/', views.CityDetailView.as_view(), name='city_detail'),
    
    path('city/<int:pk>/location/', views.CityLocationView.as_view(), name='city_location'),
    path('city/<int:pk>/showlocation/', views.city_location, name='city_location'),

    path('ajax/load-subcontinents/', views.load_subcontinents, name='ajax_load_subcontinents'),
    path('ajax/load-countries/', views.load_countries, name='ajax_load_countries'),
    path('ajax/load-states/', views.load_states, name='ajax_load_states'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),


]

regions/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.utils.translation import gettext_lazy as _
from datetime import date
from django.utils import timezone

class TimeZone(models.Model):
    
    zoneName = models.CharField(max_length=15, 
        verbose_name=_("Zone Name"), 
        help_text=_("Zone official name description (e.g. Asia/Kabul)."))

    gmtOffset = models.IntegerField(
        verbose_name=_("GMT offset"), 
        help_text=_("Number of hours or minutes a time zone is ahead of or behind GMT."))

    gmtOffsetName = models.CharField(max_length=10, 
        verbose_name=_("GMT offset name"), 
        help_text=_("GMT offset name description (e.g. UTC+04:30)."))

    abbreviation = models.CharField(max_length=6, 
        verbose_name=_("GMT offset abbreviation"), 
        help_text=_("GMT offset name abbreviation (e.g. AFT)."))

    tzName = models.CharField(max_length=55, 
        verbose_name=_("Time Zone Name"), 
        help_text=_("Time Zone Name description (e.g. Afghanistan Time)."))

    date_created = models.DateTimeField(auto_now_add=True,)
    date_mod = models.DateField(default=timezone.now, verbose_name='Date Modified')
    
    class Meta:
        #unique_together = ['name', 'code', ],
        ordering = ['zoneName']
        verbose_name_plural = 'TimeZones'

    def get_absolute_url(self):
        return reverse('timezone_detail', args=[str(self.id)])

    def __str__(self):
        return str('%s' ' (%s)' % (self.zoneName, self.gmtOffsetName))


class Continent(models.Model):

    name = models.CharField(max_length=15, 
        verbose_name=_("Continent Name"), 
        help_text=_("Continent official name description."))

    code = models.CharField(max_length=2, 
        verbose_name=_("Continent Code"), 
        help_text=_("Continent ISO3166-2 description."))

    date_created = models.DateTimeField(auto_now_add=True,)
    date_mod = models.DateField(default=timezone.now, verbose_name='Date Modified')

    class Meta:
        #unique_together = ['name', 'code', ],
        ordering = ['name']
        verbose_name_plural = 'Continents'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('continent-detail', kwargs={'pk': self.pk})

    


class SubContinent(models.Model):
    
    continent = models.ForeignKey(Continent, on_delete=models.CASCADE, 
        related_name='continent_subcontinents', 
        verbose_name=_("Continent"), help_text=_("The continent description."))

    name = models.CharField(max_length=30, 
        verbose_name=_("SubContinent Name"), 
        help_text=_("SubContinent official name description."))

    date_created = models.DateTimeField(auto_now_add=True,)
    date_mod = models.DateField(default=timezone.now, verbose_name='Date Modified')

    class Meta:
        #unique_together = ['name', 'code', ],
        ordering = ['continent']
        verbose_name_plural = 'SubContinents'

    def __str__(self):
        return self.name


    def get_absolute_url(self):
        return reverse('subcontinent_detail', kwargs={'pk': self.pk})

    


class Country(models.Model):    
    name = models.CharField(max_length=50,
        verbose_name=_("Country Name"), 
        help_text=_("Country official name description."))

    iso3 = models.CharField(max_length=3,
        verbose_name=_("ISO3166-3 Code"), 
        help_text=_("Country ISO3166-3 code description."))
    
    iso2 = models.CharField(max_length=3,
        verbose_name=_("ISO3166-2 Code"), 
        help_text=_("Country ISO3166-2 code description."))

    numeric_code = models.IntegerField(
        verbose_name=_("ISO3166-3 numeric_code"), 
        help_text=_("Country ISO3166-32 numeric_code description."))

    phone_code = models.CharField(max_length=10,
        verbose_name=_("Phone Area Calling Code"), 
        help_text=_("Country Phone Area Calling Code (+) description."))

    capital = models.CharField(max_length=30,
        verbose_name=_("Capital City"), 
        help_text=_("Country capital city name description."))

    currency = models.CharField(max_length=30,
        verbose_name=_("Country Currency"), 
        help_text=_("Country currency name description."))

    currency_symbol = models.CharField(max_length=30,
        verbose_name=_("Country Currency Symbol"), 
        help_text=_("Country currency symbol description."))

    tld = models.CharField(max_length=30,
        verbose_name=_("Country TLD"), 
        help_text=_("Country top level domain description."))

    native = models.CharField(max_length=30,
        verbose_name=_("Country native name"), 
        help_text=_("Country native name description."))

    continent = models.ForeignKey(Continent, on_delete=models.CASCADE, 
        related_name='region_countries', 
        verbose_name=_("Continent"), help_text=_("The country continent description."))

    subcontinent = models.ForeignKey(SubContinent, on_delete=models.CASCADE, 
        related_name='subregion_countries', 
        verbose_name=_("SubContinent"), help_text=_("The country subcontinent description."))

    timezones = models.ManyToManyField(TimeZone,
        verbose_name=_("Country timezones"), 
        help_text=_("Country timezones descriptions."))

    latitude = models.DecimalField(max_digits=12, decimal_places=8,
        verbose_name=_("Latitude"), help_text=_("The Latitude Coordinate."))
    
    longitude = models.DecimalField(max_digits=12, decimal_places=8,
        verbose_name=_("Longitude"), help_text=_("The Longitude Coordinate."))
    
    emoji = models.CharField(max_length=2,
        verbose_name=_("Country emoji"), 
        help_text=_("Country emoji name description."))

    emojiU = models.CharField(max_length=20,
        verbose_name=_("Country emoji unicode"), 
        help_text=_("Country emoji unicode character description."))

    flag_image = models.ImageField(upload_to='flags/', blank=True, null=True, 
        verbose_name=_("Flag Image"), help_text=_("Official flag of country"))

    map_image = models.ImageField(upload_to='maps/', blank=True, null=True, 
        verbose_name=_("Map Image"), help_text=_("Political map image of country"))

    area = models.DecimalField(max_digits=15, decimal_places=2, blank=True, null=True,
        verbose_name=_("Area square km"), help_text=_("The Area in square km.")) 

    population = models.PositiveIntegerField(blank=True, null=True,
        verbose_name=_("Population"), help_text=_("The population at time of data entry.")) 

    date_created = models.DateTimeField(auto_now_add=True,)
    date_mod = models.DateField(default=timezone.now, verbose_name='Date Modified')

    class Meta:
        #unique_together = ['continent', 'country_name', 'country_code', ],
        ordering = ['name',]
        verbose_name_plural = 'Countries'

    def get_absolute_url(self):
        return reverse('country-detail', args=[str(self.id)])

    def __str__(self):
        return self.name



class State(models.Model):

    country = models.ForeignKey(Country, on_delete=models.CASCADE, 
        related_name='country_state', 
        verbose_name=_("Country"), help_text=_("The country of the state."))

    state_name = models.CharField(max_length=30,
        verbose_name=_("State / Province / Subdivision Name"), 
        help_text=_("Country higher level sub-division (State / Province / Subdivision) description."))

    state_code = models.CharField(max_length=6, blank=True, null=True,
        verbose_name=_("State / Province / Subdivision Code"), 
        help_text=_("State / province / subdivision code description."))

    latitude = models.DecimalField(max_digits=12, decimal_places=8, blank=True, null=True,
        verbose_name=_("Latitude"), help_text=_("The Latitude Coordinate."))
    
    longitude = models.DecimalField(max_digits=12, decimal_places=8, blank=True, null=True,
        verbose_name=_("Longitude"), help_text=_("The Longitude Coordinate."))

    date_created = models.DateTimeField(auto_now_add=True,)
    date_mod = models.DateField(default=timezone.now, verbose_name='Date Modified')

    class Meta:
        #unique_together = ['country', 'name']
        ordering = ['country', 'state_name']


    def get_absolute_url(self):
        return reverse('state-detail', args=[str(self.id)])
        
    def __str__(self):
        return self.state_name


class City(models.Model):
    
    country = models.ForeignKey(Country, on_delete=models.CASCADE, 
        related_name='country_cities', 
        verbose_name=_("Country"), help_text=_("The country."))

    state = models.ForeignKey(State, on_delete=models.CASCADE, 
        related_name='state_cities', 
        verbose_name=_("State/Province"), help_text=_("The state sub-country description."))
    
    district = models.CharField(max_length=30, blank=True, null=True,
        verbose_name=_("Sub-State / County / District"),
        help_text=_("Country substates/county or sub-province description."))

    city_name = models.CharField(max_length=30,
        verbose_name=_("City or Town"),
        help_text=_("City or Town name description."))
    
    latitude = models.DecimalField(max_digits=12, decimal_places=8,
        verbose_name=_("Latitude"), help_text=_("The Latitude Coordinate."))
    
    longitude = models.DecimalField(max_digits=12, decimal_places=8,
        verbose_name=_("Longitude"), help_text=_("The Longitude Coordinate."))

    date_created = models.DateTimeField(auto_now_add=True,)
    date_mod = models.DateField(default=timezone.now, verbose_name='Date Modified')

    class Meta:
        ordering = ['country', 'state', 'city_name']
        verbose_name_plural = 'Cities'

    def get_absolute_url(self):
        return reverse('city-detail', args=[str(self.id)])

    def __str__(self):
        return self.city_name


class Region(models.Model):
    

regions/templates/regions/create/city_create.html
{% extends 'base.html' %}{% load static %}{% load bootstrap4 %} {% block content %}

<h2>New City Form<a href="{% url 'city_import' %} " class="btn btn-primary mb-2 mt-2 float-right ">Import Cities</a></h2>
<hr>
<br>
<form method="post" id="personForm" data-states-url="{% url 'ajax_load_states' %}" novalidate>
    {% csrf_token %} {% bootstrap_form form %}
    <button class="btn btn-primary btn-block" type="submit">Submit</button>

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function() {
        var url = $("#personForm").attr("data-states-url");
        var countryId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'country': countryId
            },
            success: function(data) {
                $("#id_state").html(data);
            }
        });

    });
</script>

{% endblock %}

regions/templates/regions/create/continent_create.html
{% extends 'base.html' %}{% load static %}{% load bootstrap4 %} {% block content %}

<h2>New Continent Form<a href="{% url 'continent_import' %} " class="btn btn-primary mb-2 mt-2 float-right ">Import Continent</a></h2>
<hr>
<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="btn btn-primary btn-block" type="submit">Submit</button>

</form>

{% endblock %}

regions/templates/regions/create/country_create.html
{% extends 'base.html' %}{% load static %}{% load bootstrap4 %} {% block content %}

<h2>New Country Form<a href="{% url 'country_import' %} " class="btn btn-primary mb-2 mt-2 float-right ">Import Country</a></h2>
<hr>
<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="btn btn-primary btn-block" type="submit">Submit</button>

</form>

{% endblock %}

regions/templates/regions/create/state_create.html
{% extends 'base.html' %}{% load static %}{% load bootstrap4 %} {% block content %}

<h2>New State Form<a href="{% url 'state_import' %} " class="btn btn-primary mb-2 mt-2 float-right ">Import States</a></h2>
<hr>
<br>
<form method="post" enctype="multipart/form-data" id="personForm" data-states-url="{% url 'ajax_load_states' %}" novalidate>
    {% csrf_token %} {% bootstrap_form form %}
    <button class="btn btn-primary btn-block" type="submit">Submit</button>

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function() {
        var url = $("#personForm").attr("data-states-url");
        var countryId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'country': countryId
            },
            success: function(data) {
                $("#id_state").html(data);
            }
        });

    });
</script>


{% endblock %}

regions/templates/regions/create/subcontinent_create.html
{% extends 'base.html' %}{% load static %}{% load bootstrap4 %} {% block title %}SUB CONTINENTAL MODULE{% endblock %} {% block content %}

<h2>New Sub Continent Form<a href="{% url 'subcontinent_import' %} " class="btn btn-primary mb-2 mt-2 float-right ">Import SubContinents</a></h2>
<hr>
<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="btn btn-primary btn-block" type="submit">Submit</button>

</form>

{% endblock %}

regions/templates/regions/create/timezone_create.html
{% extends 'base.html' %}{% load static %}{% load bootstrap4 %} {% block content %}

<h2>New Time Zone Form<a href="{% url 'timezone_import' %} " class="btn btn-primary mb-2 mt-2 float-right ">Import Time Zones</a></h2>
<hr>
<br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="btn btn-primary btn-block" type="submit">Submit</button>

</form>


{% endblock %}